//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLiVanBanEntities : DbContext
    {
        public QuanLiVanBanEntities()
            : base("name=QuanLiVanBanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DanhSachPhongban> DanhSachPhongbans { get; set; }
        public virtual DbSet<DiaDiem> DiaDiems { get; set; }
        public virtual DbSet<loaivanban> loaivanbans { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<thongtinvanban> thongtinvanbans { get; set; }
        public virtual DbSet<User_Page> User_Page { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VanBanDiChuyen> VanBanDiChuyens { get; set; }
    }
}
