//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongtinvanban
    {
        public int Id { get; set; }
        public Nullable<int> idLoaiVanBan { get; set; }
        public Nullable<int> IdVanBanDiChuyen { get; set; }
        public Nullable<int> IdPhongBan { get; set; }
        public string NguonVB { get; set; }
        public Nullable<int> SoVBNoiBo { get; set; }
        public string ButPhe { get; set; }
        public string TaiLieuDinhKem { get; set; }
        public Nullable<System.DateTime> NgayPhongBanSoanThao { get; set; }
        public int UserCreate { get; set; }
        public Nullable<System.DateTime> DatetimeCreate { get; set; }
        public Nullable<int> UserUpdate { get; set; }
        public Nullable<System.DateTime> DatetimeUpdate { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<int> UserDelete { get; set; }
        public Nullable<System.DateTime> DatetimeDelete { get; set; }
    }
}
