//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.User_Page = new HashSet<User_Page>();
        }
    
        public int Id { get; set; }
        public string AccoutType { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public string SoDienThoai { get; set; }
        public string HoNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string NoiSinh { get; set; }
        public string DiaChiThuongTru { get; set; }
        public string DiaChiTamTru { get; set; }
        public string DanToc { get; set; }
        public string TonGiao { get; set; }
        public Nullable<int> CCCD { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string NoiCap { get; set; }
        public string MaSoBHXH { get; set; }
        public string TrinhDoVanHoa { get; set; }
        public string TrinhDoChuyenMon { get; set; }
        public string NganhHoc { get; set; }
        public string NoiDaoTao { get; set; }
        public string TrinhDoChinhTri { get; set; }
        public Nullable<System.DateTime> NgayVaoDangDuBi { get; set; }
        public Nullable<System.DateTime> NgayVaoDangChinhThuc { get; set; }
        public string PhongBan { get; set; }
        public string ChucDanh { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> HieuLuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Page> User_Page { get; set; }
    }
}
