//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Page
    {
        public int Id { get; set; }
        public int userId { get; set; }
        public int PageId { get; set; }
        public int UserCreate { get; set; }
        public Nullable<System.DateTime> DatetimeCreate { get; set; }
        public Nullable<int> UserUpdate { get; set; }
        public Nullable<System.DateTime> DatetimeUpdate { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<int> UserDelete { get; set; }
        public Nullable<System.DateTime> DatetimeDelete { get; set; }
        public Nullable<bool> isRoleCreate { get; set; }
        public Nullable<bool> isRoleEdit { get; set; }
        public Nullable<bool> isRoleExport { get; set; }
        public Nullable<bool> isRoleExportAll { get; set; }
        public Nullable<bool> isRoleDelete { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual User User { get; set; }
    }
}
